//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPool.WS.Users.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MPOOL_HackathonEntities : DbContext
    {
        public MPOOL_HackathonEntities()
            : base("name=MPOOL_HackathonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BloodGroup> BloodGroups { get; set; }
        public virtual DbSet<BRANCH> BRANCHES { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<LOGIN> LOGINS { get; set; }
        public virtual DbSet<Routing> Routings { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<UserAddress> UserAddresses { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<VEHICLE_INFO> VEHICLE_INFO { get; set; }
        public virtual DbSet<PoolerDeparture> PoolerDepartures { get; set; }
    }
}
