//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPool.WS.Users.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.LOGINS = new HashSet<LOGIN>();
            this.UserAddresses = new HashSet<UserAddress>();
            this.VEHICLE_INFO = new HashSet<VEHICLE_INFO>();
            this.PoolerDepartures = new HashSet<PoolerDeparture>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool FirstLogin { get; set; }
        public string BranchCode { get; set; }
        public Nullable<int> RoutingId { get; set; }
        public string BloodGroupId { get; set; }
        public Nullable<long> Contact { get; set; }
        public string Emailid { get; set; }
        public string Pooler_Passanger { get; set; }
        public System.DateTime Create_on { get; set; }
        public Nullable<System.DateTime> Last_Modified_On { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGIN> LOGINS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAddress> UserAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICLE_INFO> VEHICLE_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PoolerDeparture> PoolerDepartures { get; set; }
    }
}
