//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPool.WS.Users.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICLE_INFO
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<bool> IsPooler { get; set; }
        public string Wheeler { get; set; }
        public Nullable<int> SeatsAvailability { get; set; }
        public string RouteID { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
